export default {
    products: [
        {
            _id: '1111111111111111111111111',
            name: 'BB Foundation',
            category: 'Cosmetics',
            image: '/images/product-1.jpg',
            price: 8500,
            brand: 'iKigai',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Ki Ki LipSticks',
            category: 'Cosmetics',
            image: '/images/product-2.jpg',
            price: 6500,
            brand: 'iKigai',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Ki Ki Cocorn',
            category: 'Cosmetics',
            image: '/images/product-3.jpg',
            price: 8500,
            brand: 'iKigai',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Vibe',
            category: 'Cosmetics',
            image: '/images/product-4.jpg',
            price: 4500,
            brand: 'iKigai',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Soccer Shoe',
            category: 'Shoes',
            image: '/images/product-5.jpg',
            price: 48000,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Men Backpack',
            category: 'Bags',
            image: '/images/product-6.jpg',
            price: 75600,
            brand: 'iKigai',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};